apiVersion: skaffold/v1beta5
kind: Config
build:
  artifacts:
  - image: nexenta/edgefs-csi
    context: .
    docker:
      dockerfile: Dockerfile
      buildArgs:
        REGISTRY: '{{.DOCKER_REGISTRY}}/nexenta'
        IMAGE_TAG: '{{.VERSION}}'
