apiVersion: skaffold/v1beta8
kind: Config
build:
  artifacts:
  - image: nexenta/edgefs-csi
    context: .
    docker:
      dockerfile: Dockerfile
      buildArgs:
        REGISTRY: '{{.DOCKER_REGISTRY}}/nexenta'
        IMAGE_TAG: '{{.VERSION}}'
#  tagPolicy:
#    envTemplate:
#      template: '{{.DOCKER_REGISTRY}}/nexenta/edgefs-csi:{{.VERSION}}'
