# This YAML file contains nginx & Edgfefs ISCSI ISCSI driver objects,
# which are necessary to run nginx with edgefs ISCSI csi driver.

apiVersion: v1
kind: PersistentVolume
metadata:
  name: edgefs-iscsi-csi-pv-cl-01
  labels:
    name: edgefs-iscsi-csi-pv-cl-01
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  csi:
    driver: io.edgefs.csi.iscsi
    volumeHandle: rook-edgefs-01:iscsi01@cltest/test/bk/lun1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edgefs-iscsi-csi-pvc-cl-01
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchExpressions:
    - key: name
      operator: In
      values: ["edgefs-iscsi-csi-pv-cl-01"]
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: maersk/nginx
    imagePullPolicy: Always
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    volumeMounts:
      - mountPath: /var/www
        name: edgefs-iscsi-csi-volume
  volumes:
  - name: edgefs-iscsi-csi-volume
    persistentVolumeClaim:
      claimName: edgefs-iscsi-csi-pvc-cl-01

