// Code generated by protoc-gen-go. DO NOT EDIT.
// source: snapshot.proto

package snapshot

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SnapshotInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SourceObject         string   `protobuf:"bytes,2,opt,name=sourceObject,proto3" json:"sourceObject,omitempty"`
	CreationTime         int64    `protobuf:"varint,3,opt,name=creationTime,proto3" json:"creationTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SnapshotInfo) Reset()         { *m = SnapshotInfo{} }
func (m *SnapshotInfo) String() string { return proto.CompactTextString(m) }
func (*SnapshotInfo) ProtoMessage()    {}
func (*SnapshotInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c8aab8e59648e0b, []int{0}
}

func (m *SnapshotInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SnapshotInfo.Unmarshal(m, b)
}
func (m *SnapshotInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SnapshotInfo.Marshal(b, m, deterministic)
}
func (m *SnapshotInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnapshotInfo.Merge(m, src)
}
func (m *SnapshotInfo) XXX_Size() int {
	return xxx_messageInfo_SnapshotInfo.Size(m)
}
func (m *SnapshotInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SnapshotInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SnapshotInfo proto.InternalMessageInfo

func (m *SnapshotInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SnapshotInfo) GetSourceObject() string {
	if m != nil {
		return m.SourceObject
	}
	return ""
}

func (m *SnapshotInfo) GetCreationTime() int64 {
	if m != nil {
		return m.CreationTime
	}
	return 0
}

type ObjectEntry struct {
	Cluster              string   `protobuf:"bytes,1,opt,name=Cluster,proto3" json:"Cluster,omitempty"`
	Tenant               string   `protobuf:"bytes,2,opt,name=Tenant,proto3" json:"Tenant,omitempty"`
	Bucket               string   `protobuf:"bytes,3,opt,name=Bucket,proto3" json:"Bucket,omitempty"`
	Object               string   `protobuf:"bytes,4,opt,name=Object,proto3" json:"Object,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjectEntry) Reset()         { *m = ObjectEntry{} }
func (m *ObjectEntry) String() string { return proto.CompactTextString(m) }
func (*ObjectEntry) ProtoMessage()    {}
func (*ObjectEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c8aab8e59648e0b, []int{1}
}

func (m *ObjectEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectEntry.Unmarshal(m, b)
}
func (m *ObjectEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectEntry.Marshal(b, m, deterministic)
}
func (m *ObjectEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectEntry.Merge(m, src)
}
func (m *ObjectEntry) XXX_Size() int {
	return xxx_messageInfo_ObjectEntry.Size(m)
}
func (m *ObjectEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectEntry proto.InternalMessageInfo

func (m *ObjectEntry) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *ObjectEntry) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *ObjectEntry) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *ObjectEntry) GetObject() string {
	if m != nil {
		return m.Object
	}
	return ""
}

type SnapshotEntry struct {
	Cluster              string   `protobuf:"bytes,1,opt,name=Cluster,proto3" json:"Cluster,omitempty"`
	Tenant               string   `protobuf:"bytes,2,opt,name=Tenant,proto3" json:"Tenant,omitempty"`
	Bucket               string   `protobuf:"bytes,3,opt,name=Bucket,proto3" json:"Bucket,omitempty"`
	Object               string   `protobuf:"bytes,4,opt,name=Object,proto3" json:"Object,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SnapshotEntry) Reset()         { *m = SnapshotEntry{} }
func (m *SnapshotEntry) String() string { return proto.CompactTextString(m) }
func (*SnapshotEntry) ProtoMessage()    {}
func (*SnapshotEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c8aab8e59648e0b, []int{2}
}

func (m *SnapshotEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SnapshotEntry.Unmarshal(m, b)
}
func (m *SnapshotEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SnapshotEntry.Marshal(b, m, deterministic)
}
func (m *SnapshotEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnapshotEntry.Merge(m, src)
}
func (m *SnapshotEntry) XXX_Size() int {
	return xxx_messageInfo_SnapshotEntry.Size(m)
}
func (m *SnapshotEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_SnapshotEntry.DiscardUnknown(m)
}

var xxx_messageInfo_SnapshotEntry proto.InternalMessageInfo

func (m *SnapshotEntry) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *SnapshotEntry) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *SnapshotEntry) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *SnapshotEntry) GetObject() string {
	if m != nil {
		return m.Object
	}
	return ""
}

func (m *SnapshotEntry) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SnapviewRequest struct {
	Object               *ObjectEntry `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SnapviewRequest) Reset()         { *m = SnapviewRequest{} }
func (m *SnapviewRequest) String() string { return proto.CompactTextString(m) }
func (*SnapviewRequest) ProtoMessage()    {}
func (*SnapviewRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c8aab8e59648e0b, []int{3}
}

func (m *SnapviewRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SnapviewRequest.Unmarshal(m, b)
}
func (m *SnapviewRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SnapviewRequest.Marshal(b, m, deterministic)
}
func (m *SnapviewRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnapviewRequest.Merge(m, src)
}
func (m *SnapviewRequest) XXX_Size() int {
	return xxx_messageInfo_SnapviewRequest.Size(m)
}
func (m *SnapviewRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SnapviewRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SnapviewRequest proto.InternalMessageInfo

func (m *SnapviewRequest) GetObject() *ObjectEntry {
	if m != nil {
		return m.Object
	}
	return nil
}

type SnapshotRequest struct {
	Snapshot             *SnapshotEntry `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SnapshotRequest) Reset()         { *m = SnapshotRequest{} }
func (m *SnapshotRequest) String() string { return proto.CompactTextString(m) }
func (*SnapshotRequest) ProtoMessage()    {}
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c8aab8e59648e0b, []int{4}
}

func (m *SnapshotRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SnapshotRequest.Unmarshal(m, b)
}
func (m *SnapshotRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SnapshotRequest.Marshal(b, m, deterministic)
}
func (m *SnapshotRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnapshotRequest.Merge(m, src)
}
func (m *SnapshotRequest) XXX_Size() int {
	return xxx_messageInfo_SnapshotRequest.Size(m)
}
func (m *SnapshotRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SnapshotRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SnapshotRequest proto.InternalMessageInfo

func (m *SnapshotRequest) GetSnapshot() *SnapshotEntry {
	if m != nil {
		return m.Snapshot
	}
	return nil
}

type SnapshotCloneRequest struct {
	Snapshot             *SnapshotEntry `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Clone                *ObjectEntry   `protobuf:"bytes,2,opt,name=clone,proto3" json:"clone,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SnapshotCloneRequest) Reset()         { *m = SnapshotCloneRequest{} }
func (m *SnapshotCloneRequest) String() string { return proto.CompactTextString(m) }
func (*SnapshotCloneRequest) ProtoMessage()    {}
func (*SnapshotCloneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c8aab8e59648e0b, []int{5}
}

func (m *SnapshotCloneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SnapshotCloneRequest.Unmarshal(m, b)
}
func (m *SnapshotCloneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SnapshotCloneRequest.Marshal(b, m, deterministic)
}
func (m *SnapshotCloneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnapshotCloneRequest.Merge(m, src)
}
func (m *SnapshotCloneRequest) XXX_Size() int {
	return xxx_messageInfo_SnapshotCloneRequest.Size(m)
}
func (m *SnapshotCloneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SnapshotCloneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SnapshotCloneRequest proto.InternalMessageInfo

func (m *SnapshotCloneRequest) GetSnapshot() *SnapshotEntry {
	if m != nil {
		return m.Snapshot
	}
	return nil
}

func (m *SnapshotCloneRequest) GetClone() *ObjectEntry {
	if m != nil {
		return m.Clone
	}
	return nil
}

type SnapshotListRequest struct {
	Object               *ObjectEntry `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	Pattern              string       `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Count                uint32       `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SnapshotListRequest) Reset()         { *m = SnapshotListRequest{} }
func (m *SnapshotListRequest) String() string { return proto.CompactTextString(m) }
func (*SnapshotListRequest) ProtoMessage()    {}
func (*SnapshotListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c8aab8e59648e0b, []int{6}
}

func (m *SnapshotListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SnapshotListRequest.Unmarshal(m, b)
}
func (m *SnapshotListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SnapshotListRequest.Marshal(b, m, deterministic)
}
func (m *SnapshotListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnapshotListRequest.Merge(m, src)
}
func (m *SnapshotListRequest) XXX_Size() int {
	return xxx_messageInfo_SnapshotListRequest.Size(m)
}
func (m *SnapshotListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SnapshotListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SnapshotListRequest proto.InternalMessageInfo

func (m *SnapshotListRequest) GetObject() *ObjectEntry {
	if m != nil {
		return m.Object
	}
	return nil
}

func (m *SnapshotListRequest) GetPattern() string {
	if m != nil {
		return m.Pattern
	}
	return ""
}

func (m *SnapshotListRequest) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type SnapshotListResponse struct {
	Info                 map[string]*SnapshotInfo `protobuf:"bytes,1,rep,name=info,proto3" json:"info,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *SnapshotListResponse) Reset()         { *m = SnapshotListResponse{} }
func (m *SnapshotListResponse) String() string { return proto.CompactTextString(m) }
func (*SnapshotListResponse) ProtoMessage()    {}
func (*SnapshotListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c8aab8e59648e0b, []int{7}
}

func (m *SnapshotListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SnapshotListResponse.Unmarshal(m, b)
}
func (m *SnapshotListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SnapshotListResponse.Marshal(b, m, deterministic)
}
func (m *SnapshotListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnapshotListResponse.Merge(m, src)
}
func (m *SnapshotListResponse) XXX_Size() int {
	return xxx_messageInfo_SnapshotListResponse.Size(m)
}
func (m *SnapshotListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SnapshotListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SnapshotListResponse proto.InternalMessageInfo

func (m *SnapshotListResponse) GetInfo() map[string]*SnapshotInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type SnapshotResponse struct {
	Snapshot             *SnapshotInfo `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SnapshotResponse) Reset()         { *m = SnapshotResponse{} }
func (m *SnapshotResponse) String() string { return proto.CompactTextString(m) }
func (*SnapshotResponse) ProtoMessage()    {}
func (*SnapshotResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c8aab8e59648e0b, []int{8}
}

func (m *SnapshotResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SnapshotResponse.Unmarshal(m, b)
}
func (m *SnapshotResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SnapshotResponse.Marshal(b, m, deterministic)
}
func (m *SnapshotResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnapshotResponse.Merge(m, src)
}
func (m *SnapshotResponse) XXX_Size() int {
	return xxx_messageInfo_SnapshotResponse.Size(m)
}
func (m *SnapshotResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SnapshotResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SnapshotResponse proto.InternalMessageInfo

func (m *SnapshotResponse) GetSnapshot() *SnapshotInfo {
	if m != nil {
		return m.Snapshot
	}
	return nil
}

type CloneResponse struct {
	Clone                string   `protobuf:"bytes,1,opt,name=clone,proto3" json:"clone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloneResponse) Reset()         { *m = CloneResponse{} }
func (m *CloneResponse) String() string { return proto.CompactTextString(m) }
func (*CloneResponse) ProtoMessage()    {}
func (*CloneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c8aab8e59648e0b, []int{9}
}

func (m *CloneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloneResponse.Unmarshal(m, b)
}
func (m *CloneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloneResponse.Marshal(b, m, deterministic)
}
func (m *CloneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloneResponse.Merge(m, src)
}
func (m *CloneResponse) XXX_Size() int {
	return xxx_messageInfo_CloneResponse.Size(m)
}
func (m *CloneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CloneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CloneResponse proto.InternalMessageInfo

func (m *CloneResponse) GetClone() string {
	if m != nil {
		return m.Clone
	}
	return ""
}

type GenericResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenericResponse) Reset()         { *m = GenericResponse{} }
func (m *GenericResponse) String() string { return proto.CompactTextString(m) }
func (*GenericResponse) ProtoMessage()    {}
func (*GenericResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c8aab8e59648e0b, []int{10}
}

func (m *GenericResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericResponse.Unmarshal(m, b)
}
func (m *GenericResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericResponse.Marshal(b, m, deterministic)
}
func (m *GenericResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericResponse.Merge(m, src)
}
func (m *GenericResponse) XXX_Size() int {
	return xxx_messageInfo_GenericResponse.Size(m)
}
func (m *GenericResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenericResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SnapshotInfo)(nil), "snapshot.SnapshotInfo")
	proto.RegisterType((*ObjectEntry)(nil), "snapshot.ObjectEntry")
	proto.RegisterType((*SnapshotEntry)(nil), "snapshot.SnapshotEntry")
	proto.RegisterType((*SnapviewRequest)(nil), "snapshot.SnapviewRequest")
	proto.RegisterType((*SnapshotRequest)(nil), "snapshot.SnapshotRequest")
	proto.RegisterType((*SnapshotCloneRequest)(nil), "snapshot.SnapshotCloneRequest")
	proto.RegisterType((*SnapshotListRequest)(nil), "snapshot.SnapshotListRequest")
	proto.RegisterType((*SnapshotListResponse)(nil), "snapshot.SnapshotListResponse")
	proto.RegisterMapType((map[string]*SnapshotInfo)(nil), "snapshot.SnapshotListResponse.InfoEntry")
	proto.RegisterType((*SnapshotResponse)(nil), "snapshot.SnapshotResponse")
	proto.RegisterType((*CloneResponse)(nil), "snapshot.CloneResponse")
	proto.RegisterType((*GenericResponse)(nil), "snapshot.GenericResponse")
}

func init() { proto.RegisterFile("snapshot.proto", fileDescriptor_0c8aab8e59648e0b) }

var fileDescriptor_0c8aab8e59648e0b = []byte{
	// 515 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x94, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0xc7, 0x9b, 0x7e, 0xb1, 0x9e, 0xae, 0xdd, 0x38, 0x94, 0x11, 0x2a, 0x31, 0x55, 0x96, 0x90,
	0x2a, 0x01, 0xbd, 0xe8, 0x6e, 0x10, 0xe2, 0x02, 0x51, 0x18, 0x0c, 0x21, 0x86, 0xcc, 0x5e, 0x20,
	0x8b, 0xce, 0x44, 0xb6, 0xce, 0x2e, 0xb1, 0x33, 0xd8, 0x03, 0xf0, 0x28, 0x3c, 0x06, 0xef, 0x86,
	0x1c, 0xdb, 0x49, 0x4a, 0x28, 0x42, 0x20, 0x71, 0xe7, 0x73, 0x7c, 0xfc, 0x3b, 0x1f, 0xff, 0x93,
	0xc0, 0x50, 0x89, 0x68, 0xa5, 0x3e, 0x4a, 0x3d, 0x5b, 0xa5, 0x52, 0x4b, 0xdc, 0xf2, 0x36, 0x3b,
	0x87, 0xed, 0x0f, 0xee, 0x7c, 0x24, 0xce, 0x24, 0x22, 0xb4, 0x45, 0x74, 0x49, 0x61, 0x30, 0x09,
	0xa6, 0x3d, 0x9e, 0x9f, 0x91, 0xc1, 0xb6, 0x92, 0x59, 0x1a, 0xd3, 0xf1, 0xe9, 0x39, 0xc5, 0x3a,
	0x6c, 0xe6, 0x77, 0x6b, 0x3e, 0x13, 0x13, 0xa7, 0x14, 0xe9, 0x44, 0x8a, 0x93, 0xe4, 0x92, 0xc2,
	0xd6, 0x24, 0x98, 0xb6, 0xf8, 0x9a, 0x8f, 0x49, 0xe8, 0xdb, 0xe8, 0x97, 0x42, 0xa7, 0xd7, 0x18,
	0xc2, 0x8d, 0xc5, 0x32, 0x53, 0x9a, 0x52, 0x97, 0xcd, 0x9b, 0xb8, 0x07, 0xdd, 0x13, 0x12, 0x91,
	0xf0, 0xa9, 0x9c, 0x65, 0xfc, 0xcf, 0xb3, 0xf8, 0x82, 0x74, 0x8e, 0xef, 0x71, 0x67, 0x19, 0xbf,
	0x2b, 0xad, 0x6d, 0xfd, 0xd6, 0x62, 0x5f, 0x03, 0x18, 0xf8, 0xee, 0xfe, 0x53, 0x4e, 0x33, 0xc0,
	0x77, 0x66, 0x80, 0x1d, 0x3b, 0x40, 0x73, 0x66, 0xcf, 0x60, 0xc7, 0x94, 0x71, 0x95, 0xd0, 0x67,
	0x4e, 0x9f, 0x32, 0x52, 0x1a, 0x1f, 0x41, 0x57, 0xda, 0xe7, 0xa6, 0x8e, 0xfe, 0xfc, 0xf6, 0xac,
	0x90, 0xa8, 0x32, 0x23, 0xee, 0x82, 0xd8, 0xa1, 0x25, 0x98, 0x7b, 0x4f, 0x38, 0x80, 0x42, 0x45,
	0xc7, 0xb8, 0x53, 0x32, 0xd6, 0xba, 0xe6, 0xa5, 0xdc, 0x5f, 0x60, 0xe4, 0xaf, 0x16, 0x4b, 0x29,
	0xe8, 0x5f, 0x60, 0xf8, 0x00, 0x3a, 0xb1, 0x81, 0xe4, 0x13, 0xdb, 0xd8, 0x82, 0x8d, 0x61, 0x1a,
	0x6e, 0x79, 0xce, 0xdb, 0x44, 0xe9, 0xbf, 0x9b, 0x83, 0xd1, 0x6f, 0x15, 0x69, 0x4d, 0xa9, 0x70,
	0x32, 0x79, 0x13, 0x47, 0xd0, 0x89, 0x65, 0x26, 0xac, 0x4c, 0x03, 0x6e, 0x0d, 0xf6, 0x2d, 0x28,
	0x1b, 0xb6, 0x69, 0xd5, 0x4a, 0x0a, 0x45, 0xf8, 0x14, 0xda, 0x89, 0x38, 0x93, 0x61, 0x30, 0x69,
	0x4d, 0xfb, 0xf3, 0x69, 0xbd, 0xd9, 0x6a, 0xf4, 0xcc, 0x7c, 0x1a, 0xb6, 0x90, 0xfc, 0xd5, 0xf8,
	0x18, 0x7a, 0x85, 0x0b, 0x77, 0xa1, 0x75, 0x41, 0xd7, 0x6e, 0x9f, 0xcc, 0x11, 0x1f, 0x42, 0xe7,
	0x2a, 0x5a, 0x66, 0x7e, 0x30, 0x7b, 0x75, 0xba, 0x79, 0xcd, 0x6d, 0xd0, 0x93, 0xe6, 0xe3, 0x80,
	0x1d, 0xc2, 0x6e, 0xa9, 0xaf, 0x2b, 0x71, 0x5e, 0xd3, 0x64, 0x13, 0xa8, 0xd4, 0xf7, 0x3e, 0x0c,
	0x9c, 0xae, 0x0e, 0x32, 0xf2, 0x1a, 0xd9, 0xf2, 0x9c, 0x18, 0x37, 0x61, 0xe7, 0x15, 0x09, 0x4a,
	0x93, 0xd8, 0x07, 0xce, 0xbf, 0x37, 0x61, 0xcb, 0x43, 0xf1, 0x08, 0x86, 0x0b, 0xf3, 0xe5, 0x52,
	0xe1, 0xb9, 0x5b, 0x4f, 0xed, 0x24, 0x1c, 0x8f, 0x7f, 0x75, 0x65, 0xa9, 0xac, 0x81, 0xaf, 0x61,
	0xf8, 0x82, 0x96, 0xf4, 0x67, 0xa8, 0xca, 0xd5, 0x4f, 0xf5, 0xb1, 0x06, 0xbe, 0x71, 0xbd, 0x15,
	0xa0, 0xfd, 0x3a, 0xa8, 0xba, 0xd4, 0xe3, 0xca, 0x0a, 0xaf, 0x0d, 0x85, 0x35, 0xf0, 0x3d, 0x0c,
	0x8c, 0xc0, 0xfe, 0x99, 0xc2, 0x7b, 0x9b, 0x36, 0xc0, 0xa2, 0xf6, 0x7f, 0xbf, 0x20, 0xac, 0x71,
	0xda, 0xcd, 0xff, 0xac, 0x07, 0x3f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xfd, 0x80, 0x47, 0xe3, 0x6b,
	0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SnapshotClient is the client API for Snapshot service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SnapshotClient interface {
	CreateSnapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error)
	DeleteSnapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*GenericResponse, error)
	CloneSnapshot(ctx context.Context, in *SnapshotCloneRequest, opts ...grpc.CallOption) (*CloneResponse, error)
	ListSnapshots(ctx context.Context, in *SnapshotListRequest, opts ...grpc.CallOption) (*SnapshotListResponse, error)
}

type snapshotClient struct {
	cc *grpc.ClientConn
}

func NewSnapshotClient(cc *grpc.ClientConn) SnapshotClient {
	return &snapshotClient{cc}
}

func (c *snapshotClient) CreateSnapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error) {
	out := new(SnapshotResponse)
	err := c.cc.Invoke(ctx, "/snapshot.Snapshot/CreateSnapshot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapshotClient) DeleteSnapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, "/snapshot.Snapshot/DeleteSnapshot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapshotClient) CloneSnapshot(ctx context.Context, in *SnapshotCloneRequest, opts ...grpc.CallOption) (*CloneResponse, error) {
	out := new(CloneResponse)
	err := c.cc.Invoke(ctx, "/snapshot.Snapshot/CloneSnapshot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapshotClient) ListSnapshots(ctx context.Context, in *SnapshotListRequest, opts ...grpc.CallOption) (*SnapshotListResponse, error) {
	out := new(SnapshotListResponse)
	err := c.cc.Invoke(ctx, "/snapshot.Snapshot/ListSnapshots", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SnapshotServer is the server API for Snapshot service.
type SnapshotServer interface {
	CreateSnapshot(context.Context, *SnapshotRequest) (*SnapshotResponse, error)
	DeleteSnapshot(context.Context, *SnapshotRequest) (*GenericResponse, error)
	CloneSnapshot(context.Context, *SnapshotCloneRequest) (*CloneResponse, error)
	ListSnapshots(context.Context, *SnapshotListRequest) (*SnapshotListResponse, error)
}

// UnimplementedSnapshotServer can be embedded to have forward compatible implementations.
type UnimplementedSnapshotServer struct {
}

func (*UnimplementedSnapshotServer) CreateSnapshot(ctx context.Context, req *SnapshotRequest) (*SnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSnapshot not implemented")
}
func (*UnimplementedSnapshotServer) DeleteSnapshot(ctx context.Context, req *SnapshotRequest) (*GenericResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSnapshot not implemented")
}
func (*UnimplementedSnapshotServer) CloneSnapshot(ctx context.Context, req *SnapshotCloneRequest) (*CloneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloneSnapshot not implemented")
}
func (*UnimplementedSnapshotServer) ListSnapshots(ctx context.Context, req *SnapshotListRequest) (*SnapshotListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSnapshots not implemented")
}

func RegisterSnapshotServer(s *grpc.Server, srv SnapshotServer) {
	s.RegisterService(&_Snapshot_serviceDesc, srv)
}

func _Snapshot_CreateSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotServer).CreateSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/snapshot.Snapshot/CreateSnapshot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotServer).CreateSnapshot(ctx, req.(*SnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Snapshot_DeleteSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotServer).DeleteSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/snapshot.Snapshot/DeleteSnapshot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotServer).DeleteSnapshot(ctx, req.(*SnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Snapshot_CloneSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotCloneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotServer).CloneSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/snapshot.Snapshot/CloneSnapshot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotServer).CloneSnapshot(ctx, req.(*SnapshotCloneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Snapshot_ListSnapshots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotServer).ListSnapshots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/snapshot.Snapshot/ListSnapshots",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotServer).ListSnapshots(ctx, req.(*SnapshotListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Snapshot_serviceDesc = grpc.ServiceDesc{
	ServiceName: "snapshot.Snapshot",
	HandlerType: (*SnapshotServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSnapshot",
			Handler:    _Snapshot_CreateSnapshot_Handler,
		},
		{
			MethodName: "DeleteSnapshot",
			Handler:    _Snapshot_DeleteSnapshot_Handler,
		},
		{
			MethodName: "CloneSnapshot",
			Handler:    _Snapshot_CloneSnapshot_Handler,
		},
		{
			MethodName: "ListSnapshots",
			Handler:    _Snapshot_ListSnapshots_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "snapshot.proto",
}
