// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProtocolType int32

const (
	ProtocolType_UNKNOWN ProtocolType = 0
	ProtocolType_NFS     ProtocolType = 1
	ProtocolType_S3      ProtocolType = 2
	ProtocolType_ISCSI   ProtocolType = 3
	ProtocolType_NBD     ProtocolType = 4
	ProtocolType_ISGW    ProtocolType = 5
)

var ProtocolType_name = map[int32]string{
	0: "UNKNOWN",
	1: "NFS",
	2: "S3",
	3: "ISCSI",
	4: "NBD",
	5: "ISGW",
}

var ProtocolType_value = map[string]int32{
	"UNKNOWN": 0,
	"NFS":     1,
	"S3":      2,
	"ISCSI":   3,
	"NBD":     4,
	"ISGW":    5,
}

func (x ProtocolType) String() string {
	return proto.EnumName(ProtocolType_name, int32(x))
}

func (ProtocolType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

type GenericResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenericResponse) Reset()         { *m = GenericResponse{} }
func (m *GenericResponse) String() string { return proto.CompactTextString(m) }
func (*GenericResponse) ProtoMessage()    {}
func (*GenericResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *GenericResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericResponse.Unmarshal(m, b)
}
func (m *GenericResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericResponse.Marshal(b, m, deterministic)
}
func (m *GenericResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericResponse.Merge(m, src)
}
func (m *GenericResponse) XXX_Size() int {
	return xxx_messageInfo_GenericResponse.Size(m)
}
func (m *GenericResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenericResponse proto.InternalMessageInfo

type ServiceListRequest struct {
	Pattern              string       `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Count                int32        `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Type                 ProtocolType `protobuf:"varint,3,opt,name=type,proto3,enum=service.ProtocolType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ServiceListRequest) Reset()         { *m = ServiceListRequest{} }
func (m *ServiceListRequest) String() string { return proto.CompactTextString(m) }
func (*ServiceListRequest) ProtoMessage()    {}
func (*ServiceListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *ServiceListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceListRequest.Unmarshal(m, b)
}
func (m *ServiceListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceListRequest.Marshal(b, m, deterministic)
}
func (m *ServiceListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceListRequest.Merge(m, src)
}
func (m *ServiceListRequest) XXX_Size() int {
	return xxx_messageInfo_ServiceListRequest.Size(m)
}
func (m *ServiceListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceListRequest proto.InternalMessageInfo

func (m *ServiceListRequest) GetPattern() string {
	if m != nil {
		return m.Pattern
	}
	return ""
}

func (m *ServiceListRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ServiceListRequest) GetType() ProtocolType {
	if m != nil {
		return m.Type
	}
	return ProtocolType_UNKNOWN
}

type ServiceInfo struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	//iscsi
	Iqn                  string       `protobuf:"bytes,2,opt,name=iqn,proto3" json:"iqn,omitempty"`
	Type                 ProtocolType `protobuf:"varint,3,opt,name=type,proto3,enum=service.ProtocolType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ServiceInfo) Reset()         { *m = ServiceInfo{} }
func (m *ServiceInfo) String() string { return proto.CompactTextString(m) }
func (*ServiceInfo) ProtoMessage()    {}
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *ServiceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceInfo.Unmarshal(m, b)
}
func (m *ServiceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceInfo.Marshal(b, m, deterministic)
}
func (m *ServiceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceInfo.Merge(m, src)
}
func (m *ServiceInfo) XXX_Size() int {
	return xxx_messageInfo_ServiceInfo.Size(m)
}
func (m *ServiceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceInfo proto.InternalMessageInfo

func (m *ServiceInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServiceInfo) GetIqn() string {
	if m != nil {
		return m.Iqn
	}
	return ""
}

func (m *ServiceInfo) GetType() ProtocolType {
	if m != nil {
		return m.Type
	}
	return ProtocolType_UNKNOWN
}

type ServiceListResponse struct {
	Info                 map[string]*ServiceInfo `protobuf:"bytes,1,rep,name=info,proto3" json:"info,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ServiceListResponse) Reset()         { *m = ServiceListResponse{} }
func (m *ServiceListResponse) String() string { return proto.CompactTextString(m) }
func (*ServiceListResponse) ProtoMessage()    {}
func (*ServiceListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *ServiceListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceListResponse.Unmarshal(m, b)
}
func (m *ServiceListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceListResponse.Marshal(b, m, deterministic)
}
func (m *ServiceListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceListResponse.Merge(m, src)
}
func (m *ServiceListResponse) XXX_Size() int {
	return xxx_messageInfo_ServiceListResponse.Size(m)
}
func (m *ServiceListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceListResponse proto.InternalMessageInfo

func (m *ServiceListResponse) GetInfo() map[string]*ServiceInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type ServiceObjectListRequest struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Pattern              string   `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Count                int32    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceObjectListRequest) Reset()         { *m = ServiceObjectListRequest{} }
func (m *ServiceObjectListRequest) String() string { return proto.CompactTextString(m) }
func (*ServiceObjectListRequest) ProtoMessage()    {}
func (*ServiceObjectListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *ServiceObjectListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceObjectListRequest.Unmarshal(m, b)
}
func (m *ServiceObjectListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceObjectListRequest.Marshal(b, m, deterministic)
}
func (m *ServiceObjectListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceObjectListRequest.Merge(m, src)
}
func (m *ServiceObjectListRequest) XXX_Size() int {
	return xxx_messageInfo_ServiceObjectListRequest.Size(m)
}
func (m *ServiceObjectListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceObjectListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceObjectListRequest proto.InternalMessageInfo

func (m *ServiceObjectListRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *ServiceObjectListRequest) GetPattern() string {
	if m != nil {
		return m.Pattern
	}
	return ""
}

func (m *ServiceObjectListRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ServiceObjectInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceObjectInfo) Reset()         { *m = ServiceObjectInfo{} }
func (m *ServiceObjectInfo) String() string { return proto.CompactTextString(m) }
func (*ServiceObjectInfo) ProtoMessage()    {}
func (*ServiceObjectInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *ServiceObjectInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceObjectInfo.Unmarshal(m, b)
}
func (m *ServiceObjectInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceObjectInfo.Marshal(b, m, deterministic)
}
func (m *ServiceObjectInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceObjectInfo.Merge(m, src)
}
func (m *ServiceObjectInfo) XXX_Size() int {
	return xxx_messageInfo_ServiceObjectInfo.Size(m)
}
func (m *ServiceObjectInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceObjectInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceObjectInfo proto.InternalMessageInfo

func (m *ServiceObjectInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ServiceObjectListResponse struct {
	Info                 map[string]*ServiceObjectInfo `protobuf:"bytes,1,rep,name=info,proto3" json:"info,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ServiceObjectListResponse) Reset()         { *m = ServiceObjectListResponse{} }
func (m *ServiceObjectListResponse) String() string { return proto.CompactTextString(m) }
func (*ServiceObjectListResponse) ProtoMessage()    {}
func (*ServiceObjectListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *ServiceObjectListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceObjectListResponse.Unmarshal(m, b)
}
func (m *ServiceObjectListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceObjectListResponse.Marshal(b, m, deterministic)
}
func (m *ServiceObjectListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceObjectListResponse.Merge(m, src)
}
func (m *ServiceObjectListResponse) XXX_Size() int {
	return xxx_messageInfo_ServiceObjectListResponse.Size(m)
}
func (m *ServiceObjectListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceObjectListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceObjectListResponse proto.InternalMessageInfo

func (m *ServiceObjectListResponse) GetInfo() map[string]*ServiceObjectInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type VolumeSettings struct {
	IsClonedObject bool `protobuf:"varint,1,opt,name=isClonedObject,proto3" json:"isClonedObject,omitempty"`
	//volume size in bytes
	VolumeSize           int64    `protobuf:"varint,2,opt,name=volumeSize,proto3" json:"volumeSize,omitempty"`
	ChunkSize            int32    `protobuf:"varint,3,opt,name=chunkSize,proto3" json:"chunkSize,omitempty"`
	BlockSize            int32    `protobuf:"varint,4,opt,name=blockSize,proto3" json:"blockSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VolumeSettings) Reset()         { *m = VolumeSettings{} }
func (m *VolumeSettings) String() string { return proto.CompactTextString(m) }
func (*VolumeSettings) ProtoMessage()    {}
func (*VolumeSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *VolumeSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VolumeSettings.Unmarshal(m, b)
}
func (m *VolumeSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VolumeSettings.Marshal(b, m, deterministic)
}
func (m *VolumeSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VolumeSettings.Merge(m, src)
}
func (m *VolumeSettings) XXX_Size() int {
	return xxx_messageInfo_VolumeSettings.Size(m)
}
func (m *VolumeSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_VolumeSettings.DiscardUnknown(m)
}

var xxx_messageInfo_VolumeSettings proto.InternalMessageInfo

func (m *VolumeSettings) GetIsClonedObject() bool {
	if m != nil {
		return m.IsClonedObject
	}
	return false
}

func (m *VolumeSettings) GetVolumeSize() int64 {
	if m != nil {
		return m.VolumeSize
	}
	return 0
}

func (m *VolumeSettings) GetChunkSize() int32 {
	if m != nil {
		return m.ChunkSize
	}
	return 0
}

func (m *VolumeSettings) GetBlockSize() int32 {
	if m != nil {
		return m.BlockSize
	}
	return 0
}

type ServeRequest struct {
	Type                 ProtocolType    `protobuf:"varint,1,opt,name=type,proto3,enum=service.ProtocolType" json:"type,omitempty"`
	Service              string          `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	K8SService           string          `protobuf:"bytes,3,opt,name=k8sService,proto3" json:"k8sService,omitempty"`
	K8SNamespace         string          `protobuf:"bytes,4,opt,name=k8sNamespace,proto3" json:"k8sNamespace,omitempty"`
	Cluster              string          `protobuf:"bytes,5,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Tenant               string          `protobuf:"bytes,6,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Bucket               string          `protobuf:"bytes,7,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Object               string          `protobuf:"bytes,8,opt,name=object,proto3" json:"object,omitempty"`
	VolumeId             uint32          `protobuf:"varint,9,opt,name=volumeId,proto3" json:"volumeId,omitempty"`
	VolumeSettings       *VolumeSettings `protobuf:"bytes,10,opt,name=volumeSettings,proto3" json:"volumeSettings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ServeRequest) Reset()         { *m = ServeRequest{} }
func (m *ServeRequest) String() string { return proto.CompactTextString(m) }
func (*ServeRequest) ProtoMessage()    {}
func (*ServeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{8}
}

func (m *ServeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServeRequest.Unmarshal(m, b)
}
func (m *ServeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServeRequest.Marshal(b, m, deterministic)
}
func (m *ServeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServeRequest.Merge(m, src)
}
func (m *ServeRequest) XXX_Size() int {
	return xxx_messageInfo_ServeRequest.Size(m)
}
func (m *ServeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ServeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ServeRequest proto.InternalMessageInfo

func (m *ServeRequest) GetType() ProtocolType {
	if m != nil {
		return m.Type
	}
	return ProtocolType_UNKNOWN
}

func (m *ServeRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *ServeRequest) GetK8SService() string {
	if m != nil {
		return m.K8SService
	}
	return ""
}

func (m *ServeRequest) GetK8SNamespace() string {
	if m != nil {
		return m.K8SNamespace
	}
	return ""
}

func (m *ServeRequest) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *ServeRequest) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *ServeRequest) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *ServeRequest) GetObject() string {
	if m != nil {
		return m.Object
	}
	return ""
}

func (m *ServeRequest) GetVolumeId() uint32 {
	if m != nil {
		return m.VolumeId
	}
	return 0
}

func (m *ServeRequest) GetVolumeSettings() *VolumeSettings {
	if m != nil {
		return m.VolumeSettings
	}
	return nil
}

type ServeResponse struct {
	VolumePath           string   `protobuf:"bytes,1,opt,name=volumePath,proto3" json:"volumePath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServeResponse) Reset()         { *m = ServeResponse{} }
func (m *ServeResponse) String() string { return proto.CompactTextString(m) }
func (*ServeResponse) ProtoMessage()    {}
func (*ServeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{9}
}

func (m *ServeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServeResponse.Unmarshal(m, b)
}
func (m *ServeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServeResponse.Marshal(b, m, deterministic)
}
func (m *ServeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServeResponse.Merge(m, src)
}
func (m *ServeResponse) XXX_Size() int {
	return xxx_messageInfo_ServeResponse.Size(m)
}
func (m *ServeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ServeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ServeResponse proto.InternalMessageInfo

func (m *ServeResponse) GetVolumePath() string {
	if m != nil {
		return m.VolumePath
	}
	return ""
}

type SetParamRequest struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Tenant               string   `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetParamRequest) Reset()         { *m = SetParamRequest{} }
func (m *SetParamRequest) String() string { return proto.CompactTextString(m) }
func (*SetParamRequest) ProtoMessage()    {}
func (*SetParamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{10}
}

func (m *SetParamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetParamRequest.Unmarshal(m, b)
}
func (m *SetParamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetParamRequest.Marshal(b, m, deterministic)
}
func (m *SetParamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetParamRequest.Merge(m, src)
}
func (m *SetParamRequest) XXX_Size() int {
	return xxx_messageInfo_SetParamRequest.Size(m)
}
func (m *SetParamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetParamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetParamRequest proto.InternalMessageInfo

func (m *SetParamRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *SetParamRequest) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func init() {
	proto.RegisterEnum("service.ProtocolType", ProtocolType_name, ProtocolType_value)
	proto.RegisterType((*GenericResponse)(nil), "service.GenericResponse")
	proto.RegisterType((*ServiceListRequest)(nil), "service.ServiceListRequest")
	proto.RegisterType((*ServiceInfo)(nil), "service.ServiceInfo")
	proto.RegisterType((*ServiceListResponse)(nil), "service.ServiceListResponse")
	proto.RegisterMapType((map[string]*ServiceInfo)(nil), "service.ServiceListResponse.InfoEntry")
	proto.RegisterType((*ServiceObjectListRequest)(nil), "service.ServiceObjectListRequest")
	proto.RegisterType((*ServiceObjectInfo)(nil), "service.ServiceObjectInfo")
	proto.RegisterType((*ServiceObjectListResponse)(nil), "service.ServiceObjectListResponse")
	proto.RegisterMapType((map[string]*ServiceObjectInfo)(nil), "service.ServiceObjectListResponse.InfoEntry")
	proto.RegisterType((*VolumeSettings)(nil), "service.VolumeSettings")
	proto.RegisterType((*ServeRequest)(nil), "service.ServeRequest")
	proto.RegisterType((*ServeResponse)(nil), "service.ServeResponse")
	proto.RegisterType((*SetParamRequest)(nil), "service.SetParamRequest")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 716 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0x8d, 0x9d, 0x5f, 0x4f, 0xda, 0x34, 0x9d, 0xaf, 0xed, 0x67, 0x42, 0x55, 0x05, 0x5f, 0x94,
	0x50, 0xa1, 0x82, 0xd2, 0x9b, 0xa8, 0x42, 0xa2, 0xa2, 0x40, 0x95, 0x02, 0x69, 0x65, 0x53, 0x7a,
	0x83, 0x90, 0x1c, 0x77, 0x4b, 0x4d, 0x92, 0x75, 0x1a, 0xaf, 0x23, 0x85, 0xe7, 0xe0, 0x01, 0x78,
	0x06, 0x1e, 0x86, 0xb7, 0xe0, 0x1d, 0x90, 0x77, 0xd7, 0xae, 0xed, 0xa6, 0xa9, 0xb8, 0xdb, 0x39,
	0xb3, 0xf3, 0xb3, 0xe7, 0x8c, 0xc7, 0xb0, 0xec, 0x93, 0xc9, 0xd4, 0x75, 0xc8, 0xee, 0x78, 0xe2,
	0x31, 0x0f, 0xcb, 0xd2, 0x34, 0x56, 0x61, 0xe5, 0x88, 0x50, 0x32, 0x71, 0x1d, 0x93, 0xf8, 0x63,
	0x8f, 0xfa, 0xc4, 0xf0, 0x00, 0x2d, 0xe1, 0x7d, 0xef, 0xfa, 0xcc, 0x24, 0xd7, 0x01, 0xf1, 0x19,
	0xea, 0x50, 0x1e, 0xdb, 0x8c, 0x91, 0x09, 0xd5, 0x95, 0xa6, 0xd2, 0xd2, 0xcc, 0xc8, 0xc4, 0x35,
	0x28, 0x3a, 0x5e, 0x40, 0x99, 0xae, 0x36, 0x95, 0x56, 0xd1, 0x14, 0x06, 0x3e, 0x81, 0x02, 0x9b,
	0x8d, 0x89, 0x9e, 0x6f, 0x2a, 0xad, 0x5a, 0x7b, 0x7d, 0x37, 0xaa, 0x7f, 0x1a, 0xd6, 0x77, 0xbc,
	0xe1, 0xc7, 0xd9, 0x98, 0x98, 0xfc, 0x8a, 0xf1, 0x05, 0xaa, 0xb2, 0x60, 0x97, 0x5e, 0x7a, 0x88,
	0x50, 0xa0, 0xf6, 0x88, 0xc8, 0x32, 0xfc, 0x8c, 0x75, 0xc8, 0xbb, 0xd7, 0x94, 0x57, 0xd0, 0xcc,
	0xf0, 0xf8, 0x2f, 0xf9, 0x7f, 0x2a, 0xf0, 0x5f, 0xea, 0x45, 0xe2, 0xa1, 0xb8, 0x0f, 0x05, 0x97,
	0x5e, 0x7a, 0xba, 0xd2, 0xcc, 0xb7, 0xaa, 0xed, 0xed, 0x38, 0xc5, 0x9c, 0xbb, 0xbb, 0x61, 0x67,
	0x6f, 0x28, 0x9b, 0xcc, 0x4c, 0x1e, 0xd3, 0xf8, 0x00, 0x5a, 0x0c, 0x85, 0xdd, 0x0d, 0xc8, 0x4c,
	0x36, 0x1c, 0x1e, 0x71, 0x07, 0x8a, 0x53, 0x7b, 0x18, 0x10, 0xde, 0x71, 0xb5, 0xbd, 0x96, 0xcd,
	0x1d, 0xc6, 0x9a, 0xe2, 0xca, 0xbe, 0xda, 0x51, 0x8c, 0x0b, 0xd0, 0xa5, 0xe7, 0xa4, 0xff, 0x8d,
	0x38, 0x2c, 0xc3, 0xbc, 0x8c, 0x8e, 0x98, 0x97, 0x66, 0x52, 0x13, 0xf5, 0x0e, 0x4d, 0xf2, 0x09,
	0x4d, 0x8c, 0xc7, 0xb0, 0x9a, 0xaa, 0x72, 0x17, 0xdd, 0xc6, 0x2f, 0x05, 0x1e, 0xcc, 0xe9, 0x47,
	0xf2, 0x76, 0x90, 0xe2, 0xed, 0x69, 0xf6, 0x6d, 0xb7, 0x23, 0x6e, 0xb1, 0x67, 0x2d, 0x66, 0xef,
	0x79, 0x9a, 0xbd, 0xc6, 0xfc, 0x0a, 0x59, 0x0e, 0x7f, 0x28, 0x50, 0xfb, 0xe4, 0x0d, 0x83, 0x11,
	0xb1, 0x08, 0x63, 0x2e, 0xfd, 0xea, 0xe3, 0x36, 0xd4, 0x5c, 0xff, 0x70, 0xe8, 0x51, 0x72, 0x21,
	0x62, 0x78, 0x95, 0x8a, 0x99, 0x41, 0x71, 0x0b, 0x60, 0x2a, 0x22, 0xdd, 0xef, 0xa2, 0x6a, 0xde,
	0x4c, 0x20, 0xb8, 0x09, 0x9a, 0x73, 0x15, 0xd0, 0x01, 0x77, 0x0b, 0x4a, 0x6f, 0x80, 0xd0, 0xdb,
	0x1f, 0x7a, 0x8e, 0xf0, 0x16, 0x84, 0x37, 0x06, 0x8c, 0xdf, 0x2a, 0x2c, 0x85, 0x7d, 0x93, 0x48,
	0xcf, 0x68, 0x72, 0x95, 0x7b, 0x27, 0x37, 0x29, 0xbd, 0x9a, 0x96, 0x7e, 0x0b, 0x60, 0xd0, 0xf1,
	0x25, 0x1f, 0xbc, 0x25, 0xcd, 0x4c, 0x20, 0x68, 0xc0, 0xd2, 0xa0, 0xe3, 0xf7, 0xec, 0x11, 0xf1,
	0xc7, 0xb6, 0x23, 0xda, 0xd2, 0xcc, 0x14, 0x16, 0x66, 0x77, 0x86, 0x81, 0xcf, 0xc8, 0x44, 0x2f,
	0x8a, 0xec, 0xd2, 0xc4, 0x0d, 0x28, 0x31, 0x42, 0x6d, 0xca, 0xf4, 0x12, 0x77, 0x48, 0x2b, 0xc4,
	0xfb, 0x81, 0x33, 0x20, 0x4c, 0x2f, 0x0b, 0x5c, 0x58, 0x21, 0xee, 0x09, 0x7e, 0x2b, 0x02, 0x17,
	0x16, 0x36, 0xa0, 0x22, 0x58, 0xec, 0x5e, 0xe8, 0x5a, 0x53, 0x69, 0x2d, 0x9b, 0xb1, 0x8d, 0x2f,
	0xa1, 0x36, 0x4d, 0xa9, 0xa5, 0x03, 0x57, 0xfb, 0xff, 0x98, 0x90, 0xb4, 0x98, 0x66, 0xe6, 0xba,
	0xf1, 0x0c, 0x96, 0x25, 0xaf, 0x72, 0x2e, 0x63, 0x15, 0x4f, 0x6d, 0x76, 0x25, 0xe7, 0x29, 0x81,
	0x18, 0x87, 0xb0, 0x62, 0x11, 0x76, 0x6a, 0x4f, 0xec, 0xd1, 0xfd, 0xdf, 0xd6, 0x0d, 0x05, 0x6a,
	0x92, 0x82, 0x9d, 0x63, 0x58, 0x4a, 0x0a, 0x85, 0x55, 0x28, 0x9f, 0xf5, 0xde, 0xf5, 0x4e, 0xce,
	0x7b, 0xf5, 0x1c, 0x96, 0x21, 0xdf, 0x7b, 0x6b, 0xd5, 0x15, 0x2c, 0x81, 0x6a, 0xed, 0xd5, 0x55,
	0xd4, 0xa0, 0xd8, 0xb5, 0x0e, 0xad, 0x6e, 0x3d, 0xcf, 0x7d, 0xaf, 0x5e, 0xd7, 0x0b, 0x58, 0x81,
	0x42, 0xd7, 0x3a, 0x3a, 0xaf, 0x17, 0xdb, 0x7f, 0x54, 0x28, 0x47, 0x82, 0x75, 0xa0, 0xc8, 0x5f,
	0x83, 0xeb, 0xa9, 0x69, 0x8f, 0xa6, 0xa6, 0xb1, 0x91, 0x85, 0xe5, 0xb6, 0xce, 0xe1, 0x0b, 0x28,
	0x9f, 0x51, 0x7f, 0x51, 0xac, 0x1e, 0xc3, 0xd9, 0x5d, 0x9f, 0xc3, 0x03, 0xa8, 0x44, 0xa4, 0xa0,
	0x9e, 0x08, 0x4f, 0xf1, 0xb4, 0x30, 0xc3, 0x71, 0xbc, 0xbe, 0xc3, 0x6f, 0x1e, 0x1f, 0xce, 0xdf,
	0xa3, 0x22, 0xcf, 0xe6, 0xa2, 0x25, 0x6b, 0xe4, 0xf0, 0x73, 0x66, 0x43, 0xf1, 0x8c, 0x8f, 0x16,
	0x6d, 0x18, 0x91, 0xd7, 0xb8, 0x7f, 0x09, 0x19, 0xb9, 0x7e, 0x89, 0xff, 0xfc, 0xf6, 0xfe, 0x06,
	0x00, 0x00, 0xff, 0xff, 0x7a, 0x38, 0x0d, 0x90, 0x0d, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceClient interface {
	Serve(ctx context.Context, in *ServeRequest, opts ...grpc.CallOption) (*ServeResponse, error)
	Unserve(ctx context.Context, in *ServeRequest, opts ...grpc.CallOption) (*GenericResponse, error)
	SetParam(ctx context.Context, in *SetParamRequest, opts ...grpc.CallOption) (*GenericResponse, error)
	ServiceList(ctx context.Context, in *ServiceListRequest, opts ...grpc.CallOption) (*ServiceListResponse, error)
	ServiceObjectList(ctx context.Context, in *ServiceObjectListRequest, opts ...grpc.CallOption) (*ServiceObjectListResponse, error)
}

type serviceClient struct {
	cc *grpc.ClientConn
}

func NewServiceClient(cc *grpc.ClientConn) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) Serve(ctx context.Context, in *ServeRequest, opts ...grpc.CallOption) (*ServeResponse, error) {
	out := new(ServeResponse)
	err := c.cc.Invoke(ctx, "/service.Service/Serve", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) Unserve(ctx context.Context, in *ServeRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, "/service.Service/Unserve", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) SetParam(ctx context.Context, in *SetParamRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, "/service.Service/SetParam", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) ServiceList(ctx context.Context, in *ServiceListRequest, opts ...grpc.CallOption) (*ServiceListResponse, error) {
	out := new(ServiceListResponse)
	err := c.cc.Invoke(ctx, "/service.Service/ServiceList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) ServiceObjectList(ctx context.Context, in *ServiceObjectListRequest, opts ...grpc.CallOption) (*ServiceObjectListResponse, error) {
	out := new(ServiceObjectListResponse)
	err := c.cc.Invoke(ctx, "/service.Service/ServiceObjectList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
type ServiceServer interface {
	Serve(context.Context, *ServeRequest) (*ServeResponse, error)
	Unserve(context.Context, *ServeRequest) (*GenericResponse, error)
	SetParam(context.Context, *SetParamRequest) (*GenericResponse, error)
	ServiceList(context.Context, *ServiceListRequest) (*ServiceListResponse, error)
	ServiceObjectList(context.Context, *ServiceObjectListRequest) (*ServiceObjectListResponse, error)
}

// UnimplementedServiceServer can be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (*UnimplementedServiceServer) Serve(ctx context.Context, req *ServeRequest) (*ServeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Serve not implemented")
}
func (*UnimplementedServiceServer) Unserve(ctx context.Context, req *ServeRequest) (*GenericResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unserve not implemented")
}
func (*UnimplementedServiceServer) SetParam(ctx context.Context, req *SetParamRequest) (*GenericResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetParam not implemented")
}
func (*UnimplementedServiceServer) ServiceList(ctx context.Context, req *ServiceListRequest) (*ServiceListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServiceList not implemented")
}
func (*UnimplementedServiceServer) ServiceObjectList(ctx context.Context, req *ServiceObjectListRequest) (*ServiceObjectListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServiceObjectList not implemented")
}

func RegisterServiceServer(s *grpc.Server, srv ServiceServer) {
	s.RegisterService(&_Service_serviceDesc, srv)
}

func _Service_Serve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Serve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Service/Serve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Serve(ctx, req.(*ServeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_Unserve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Unserve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Service/Unserve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Unserve(ctx, req.(*ServeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_SetParam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetParamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).SetParam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Service/SetParam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).SetParam(ctx, req.(*SetParamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_ServiceList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).ServiceList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Service/ServiceList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).ServiceList(ctx, req.(*ServiceListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_ServiceObjectList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceObjectListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).ServiceObjectList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Service/ServiceObjectList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).ServiceObjectList(ctx, req.(*ServiceObjectListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Serve",
			Handler:    _Service_Serve_Handler,
		},
		{
			MethodName: "Unserve",
			Handler:    _Service_Unserve_Handler,
		},
		{
			MethodName: "SetParam",
			Handler:    _Service_SetParam_Handler,
		},
		{
			MethodName: "ServiceList",
			Handler:    _Service_ServiceList_Handler,
		},
		{
			MethodName: "ServiceObjectList",
			Handler:    _Service_ServiceObjectList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
