# This YAML file contains nginx & Edgfefs NFS CSI driver objects,
# which are necessary to run nginx with edgefs nfs csi driver.

apiVersion: v1
kind: PersistentVolume
metadata:
  name: edgefs-nfs-csi-pv-cluster-01
  labels:
    name: edgefs-nfs-csi-pv-cluster-01
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  csi:
    driver: io.edgefs.csi.nfs
    volumeHandle: :nfs01@cltest/test/bk01
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edgefs-nfs-csi-pvc-cluster-01
  namespace: rook-edgefs-01
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchExpressions:
    - key: name
      operator: In
      values: ["edgefs-nfs-csi-pv-cluster-01"]
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: rook-edgefs-01 
spec:
  containers:
  - image: maersk/nginx
    imagePullPolicy: Always
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    volumeMounts:
      - mountPath: /var/www
        name: edgefs-nfs-csi-volume
  volumes:
  - name: edgefs-nfs-csi-volume
    persistentVolumeClaim:
      claimName: edgefs-nfs-csi-pvc-cluster-01

